#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     MyFriendlyIR,   sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     ArmExtender,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     ArmRaiser,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

// Buttons:
#define button1   0x01
#define button2   0x02
#define button3   0x04
#define button4   0x08
#define button5   0x10
#define button6   0x20
#define button7   0x40
#define button8   0x80
#define button9  0x100
#define button10 0x200


//Scales joysticks on Log scale for precise slow movement
const bool bLogarithmicScale = true;
const bool kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.

int scaleJoystick(int &nJoy1, int nMaxValue = kMaximumPowerLevel)
{
	//
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings.
	//
	static const int nLogScale[17] =
	{
		0,   5,   9,   10,
		12,  15,  18,  24,
		30,  36,  43,  50,
		60,  72,  85, 100,
		100
	};
	int nScaled;

	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
		nScaled /= 8;
		if (nScaled >= 0)
			nScaled = nLogScale[nScaled];
		else
			nScaled = - nLogScale[ - nScaled];
	}
	nScaled *= nMaxValue;
	nScaled /= 100;
	return nScaled;
}


void SetCrane(int setPowLeft, int setPowRight)
{
	motor[ArmExtender] =  setPowRight;
	motor[ArmRaiser]  =  setPowLeft;
}

void ArmControl(int y1, int y2)
{
	int powLeft = -(scaleJoystick(y1));   // Left  hand joystick, y value.
	int powRight = (scaleJoystick(y2));   // Right hand joystick, y value.

	SetCrane(powLeft, powRight);
}
void SetMotors(int setPowLeft, int setPowRight)
{
	motor[driveRight] =  setPowRight;
	motor[driveLeft]  =  setPowLeft;
}


void Tank(int y1, int y2)
{
	int powLeft = -(scaleJoystick(y1));   // Left  hand joystick, y value.
	int powRight = (scaleJoystick(y2));   // Right hand joystick, y value.

	SetMotors(powLeft, powRight);

}


 task main()
{


	while(true)
	{

	   getJoystickSettings(joystick);

	   Tank(joystick.joy1_y1,joystick.joy1_y2);
     ArmControl(joystick.joy2_y1,joystick.joy2_y2);



 }



/*  //int IR1value = SensorValue(MyFriendlyIR);
	  //nxtDisplayCenteredBigTextLine( 5, "%d", IR1value );






			//Anthing below the IR data is irrelevant





			if(joystick1.joy1_y1(1) == 128)
	  	{
	  	nxtDisplayCenteredBigTextLine( 5, "joystick1Btn1", 1 );

	  	motor[driveRight]= 25;
		  }
		else
			{
			motor[driveRight]= 0;
		  }
		  */
  }// end while
