#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     MyFriendlyIR,   sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     Gyro,           sensorAnalogInactive)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     ArmExtender,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     ArmRaiser,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
// 					User Control Mode A - from http://www.robotc.net/wiki/TETRIX_FTC_Templates
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#include "lib/common6819.c"			// Team 6819 methods library.  Common between autonomous and user control mode.

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//    Support Methods - Lower level commands we'll use to command our robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{

  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	// Play to indicate we are ready to go.
  Muppets();

	return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Routine
//
// The following is the main code for the autonomous robot operation.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program
// and run the program defined as our User Control Script.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();

  while( true ) {

  	// User Control code goes here.

  	// Drive manually
		Tank(joystick.joy1_y1, joystick.joy1_y2);
    ArmControl(joystick.joy2_y1,joystick.joy2_y2);

 	}

	return;
}
